version: "3.7"

services:
    app:
        container_name: node-mongo
        restart: always
        build: .
        ports:
            - "5000:3000"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mongodb
        image: mongo
        ports:
            - "27018:27017"
        logging:
            driver: none
